// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gostore/gostore/common (interfaces: ObjectStore)
//
// Generated by this command:
//
//	mockgen -package mocks -destination ../mocks/object_store.go github.com/gostore/gostore/common ObjectStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	common "github.com/gostore/gostore/common"
	gomock "go.uber.org/mock/gomock"
)

// MockObjectStore is a mock of ObjectStore interface.
type MockObjectStore struct {
	ctrl     *gomock.Controller
	recorder *MockObjectStoreMockRecorder
	isgomock struct{}
}

// MockObjectStoreMockRecorder is the mock recorder for MockObjectStore.
type MockObjectStoreMockRecorder struct {
	mock *MockObjectStore
}

// NewMockObjectStore creates a new mock instance.
func NewMockObjectStore(ctrl *gomock.Controller) *MockObjectStore {
	mock := &MockObjectStore{ctrl: ctrl}
	mock.recorder = &MockObjectStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectStore) EXPECT() *MockObjectStoreMockRecorder {
	return m.recorder
}

// All mocks base method.
func (m *MockObjectStore) All(count, skip int, store string) (common.ObjectRows, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All", count, skip, store)
	ret0, _ := ret[0].(common.ObjectRows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// All indicates an expected call of All.
func (mr *MockObjectStoreMockRecorder) All(count, skip, store any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*MockObjectStore)(nil).All), count, skip, store)
}

// AllCursor mocks base method.
func (m *MockObjectStore) AllCursor(store string) (common.ObjectRows, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllCursor", store)
	ret0, _ := ret[0].(common.ObjectRows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllCursor indicates an expected call of AllCursor.
func (mr *MockObjectStoreMockRecorder) AllCursor(store any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllCursor", reflect.TypeOf((*MockObjectStore)(nil).AllCursor), store)
}

// AllWithinRange mocks base method.
func (m *MockObjectStore) AllWithinRange(filter map[string]any, count, skip int, store string, opts common.ObjectStoreOptions) (common.ObjectRows, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllWithinRange", filter, count, skip, store, opts)
	ret0, _ := ret[0].(common.ObjectRows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllWithinRange indicates an expected call of AllWithinRange.
func (mr *MockObjectStoreMockRecorder) AllWithinRange(filter, count, skip, store, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllWithinRange", reflect.TypeOf((*MockObjectStore)(nil).AllWithinRange), filter, count, skip, store, opts)
}

// BatchDelete mocks base method.
func (m *MockObjectStore) BatchDelete(ids []any, store string, opts common.ObjectStoreOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelete", ids, store, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDelete indicates an expected call of BatchDelete.
func (mr *MockObjectStoreMockRecorder) BatchDelete(ids, store, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockObjectStore)(nil).BatchDelete), ids, store, opts)
}

// BatchFilterDelete mocks base method.
func (m *MockObjectStore) BatchFilterDelete(filter []map[string]any, store string, opts common.ObjectStoreOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchFilterDelete", filter, store, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchFilterDelete indicates an expected call of BatchFilterDelete.
func (mr *MockObjectStoreMockRecorder) BatchFilterDelete(filter, store, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchFilterDelete", reflect.TypeOf((*MockObjectStore)(nil).BatchFilterDelete), filter, store, opts)
}

// BatchInsert mocks base method.
func (m *MockObjectStore) BatchInsert(data []any, store string, opts common.ObjectStoreOptions) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchInsert", data, store, opts)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchInsert indicates an expected call of BatchInsert.
func (mr *MockObjectStoreMockRecorder) BatchInsert(data, store, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchInsert", reflect.TypeOf((*MockObjectStore)(nil).BatchInsert), data, store, opts)
}

// BatchUpdate mocks base method.
func (m *MockObjectStore) BatchUpdate(id, data []any, store string, opts common.ObjectStoreOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdate", id, data, store, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdate indicates an expected call of BatchUpdate.
func (mr *MockObjectStoreMockRecorder) BatchUpdate(id, data, store, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdate", reflect.TypeOf((*MockObjectStore)(nil).BatchUpdate), id, data, store, opts)
}

// Before mocks base method.
func (m *MockObjectStore) Before(id string, count, skip int, store string) (common.ObjectRows, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Before", id, count, skip, store)
	ret0, _ := ret[0].(common.ObjectRows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Before indicates an expected call of Before.
func (mr *MockObjectStoreMockRecorder) Before(id, count, skip, store any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Before", reflect.TypeOf((*MockObjectStore)(nil).Before), id, count, skip, store)
}

// Close mocks base method.
func (m *MockObjectStore) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockObjectStoreMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockObjectStore)(nil).Close))
}

// CreateDatabase mocks base method.
func (m *MockObjectStore) CreateDatabase() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDatabase")
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDatabase indicates an expected call of CreateDatabase.
func (mr *MockObjectStoreMockRecorder) CreateDatabase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDatabase", reflect.TypeOf((*MockObjectStore)(nil).CreateDatabase))
}

// CreateTable mocks base method.
func (m *MockObjectStore) CreateTable(table string, sample any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTable", table, sample)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTable indicates an expected call of CreateTable.
func (mr *MockObjectStoreMockRecorder) CreateTable(table, sample any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTable", reflect.TypeOf((*MockObjectStore)(nil).CreateTable), table, sample)
}

// Delete mocks base method.
func (m *MockObjectStore) Delete(key, store string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", key, store)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockObjectStoreMockRecorder) Delete(key, store any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockObjectStore)(nil).Delete), key, store)
}

// FilterBefore mocks base method.
func (m *MockObjectStore) FilterBefore(id string, filter map[string]any, count, skip int, store string, opts common.ObjectStoreOptions) (common.ObjectRows, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterBefore", id, filter, count, skip, store, opts)
	ret0, _ := ret[0].(common.ObjectRows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterBefore indicates an expected call of FilterBefore.
func (mr *MockObjectStoreMockRecorder) FilterBefore(id, filter, count, skip, store, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterBefore", reflect.TypeOf((*MockObjectStore)(nil).FilterBefore), id, filter, count, skip, store, opts)
}

// FilterBeforeCount mocks base method.
func (m *MockObjectStore) FilterBeforeCount(id string, filter map[string]any, count, skip int, store string, opts common.ObjectStoreOptions) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterBeforeCount", id, filter, count, skip, store, opts)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterBeforeCount indicates an expected call of FilterBeforeCount.
func (mr *MockObjectStoreMockRecorder) FilterBeforeCount(id, filter, count, skip, store, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterBeforeCount", reflect.TypeOf((*MockObjectStore)(nil).FilterBeforeCount), id, filter, count, skip, store, opts)
}

// FilterCount mocks base method.
func (m *MockObjectStore) FilterCount(filter map[string]any, store string, opts common.ObjectStoreOptions) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterCount", filter, store, opts)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterCount indicates an expected call of FilterCount.
func (mr *MockObjectStoreMockRecorder) FilterCount(filter, store, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterCount", reflect.TypeOf((*MockObjectStore)(nil).FilterCount), filter, store, opts)
}

// FilterDelete mocks base method.
func (m *MockObjectStore) FilterDelete(filter map[string]any, store string, opts common.ObjectStoreOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterDelete", filter, store, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// FilterDelete indicates an expected call of FilterDelete.
func (mr *MockObjectStoreMockRecorder) FilterDelete(filter, store, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterDelete", reflect.TypeOf((*MockObjectStore)(nil).FilterDelete), filter, store, opts)
}

// FilterGet mocks base method.
func (m *MockObjectStore) FilterGet(filter map[string]any, store string, dst any, opts common.ObjectStoreOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterGet", filter, store, dst, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// FilterGet indicates an expected call of FilterGet.
func (mr *MockObjectStoreMockRecorder) FilterGet(filter, store, dst, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterGet", reflect.TypeOf((*MockObjectStore)(nil).FilterGet), filter, store, dst, opts)
}

// FilterGetAll mocks base method.
func (m *MockObjectStore) FilterGetAll(filter map[string]any, count, skip int, store string, opts common.ObjectStoreOptions) (common.ObjectRows, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterGetAll", filter, count, skip, store, opts)
	ret0, _ := ret[0].(common.ObjectRows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterGetAll indicates an expected call of FilterGetAll.
func (mr *MockObjectStoreMockRecorder) FilterGetAll(filter, count, skip, store, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterGetAll", reflect.TypeOf((*MockObjectStore)(nil).FilterGetAll), filter, count, skip, store, opts)
}

// FilterReplace mocks base method.
func (m *MockObjectStore) FilterReplace(filter map[string]any, src any, store string, opts common.ObjectStoreOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterReplace", filter, src, store, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// FilterReplace indicates an expected call of FilterReplace.
func (mr *MockObjectStoreMockRecorder) FilterReplace(filter, src, store, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterReplace", reflect.TypeOf((*MockObjectStore)(nil).FilterReplace), filter, src, store, opts)
}

// FilterSince mocks base method.
func (m *MockObjectStore) FilterSince(id string, filter map[string]any, count, skip int, store string, opts common.ObjectStoreOptions) (common.ObjectRows, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterSince", id, filter, count, skip, store, opts)
	ret0, _ := ret[0].(common.ObjectRows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterSince indicates an expected call of FilterSince.
func (mr *MockObjectStoreMockRecorder) FilterSince(id, filter, count, skip, store, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterSince", reflect.TypeOf((*MockObjectStore)(nil).FilterSince), id, filter, count, skip, store, opts)
}

// FilterUpdate mocks base method.
func (m *MockObjectStore) FilterUpdate(filter map[string]any, src any, store string, opts common.ObjectStoreOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterUpdate", filter, src, store, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// FilterUpdate indicates an expected call of FilterUpdate.
func (mr *MockObjectStoreMockRecorder) FilterUpdate(filter, src, store, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterUpdate", reflect.TypeOf((*MockObjectStore)(nil).FilterUpdate), filter, src, store, opts)
}

// Get mocks base method.
func (m *MockObjectStore) Get(key, store string, dst any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key, store, dst)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockObjectStoreMockRecorder) Get(key, store, dst any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockObjectStore)(nil).Get), key, store, dst)
}

// GetByField mocks base method.
func (m *MockObjectStore) GetByField(name, val, store string, dst any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByField", name, val, store, dst)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetByField indicates an expected call of GetByField.
func (mr *MockObjectStoreMockRecorder) GetByField(name, val, store, dst any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByField", reflect.TypeOf((*MockObjectStore)(nil).GetByField), name, val, store, dst)
}

// GetByFieldsByField mocks base method.
func (m *MockObjectStore) GetByFieldsByField(name, val, store string, fields []string, dst any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByFieldsByField", name, val, store, fields, dst)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetByFieldsByField indicates an expected call of GetByFieldsByField.
func (mr *MockObjectStoreMockRecorder) GetByFieldsByField(name, val, store, fields, dst any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByFieldsByField", reflect.TypeOf((*MockObjectStore)(nil).GetByFieldsByField), name, val, store, fields, dst)
}

// GetStore mocks base method.
func (m *MockObjectStore) GetStore() any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStore")
	ret0, _ := ret[0].(any)
	return ret0
}

// GetStore indicates an expected call of GetStore.
func (mr *MockObjectStoreMockRecorder) GetStore() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStore", reflect.TypeOf((*MockObjectStore)(nil).GetStore))
}

// Query mocks base method.
func (m *MockObjectStore) Query(filter, aggregates map[string]any, count, skip int, store string, opts common.ObjectStoreOptions) (common.ObjectRows, common.AggregateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", filter, aggregates, count, skip, store, opts)
	ret0, _ := ret[0].(common.ObjectRows)
	ret1, _ := ret[1].(common.AggregateResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Query indicates an expected call of Query.
func (mr *MockObjectStoreMockRecorder) Query(filter, aggregates, count, skip, store, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockObjectStore)(nil).Query), filter, aggregates, count, skip, store, opts)
}

// Replace mocks base method.
func (m *MockObjectStore) Replace(key, store string, src any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Replace", key, store, src)
	ret0, _ := ret[0].(error)
	return ret0
}

// Replace indicates an expected call of Replace.
func (mr *MockObjectStoreMockRecorder) Replace(key, store, src any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Replace", reflect.TypeOf((*MockObjectStore)(nil).Replace), key, store, src)
}

// Save mocks base method.
func (m *MockObjectStore) Save(key, store string, src any) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", key, store, src)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockObjectStoreMockRecorder) Save(key, store, src any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockObjectStore)(nil).Save), key, store, src)
}

// SaveAll mocks base method.
func (m *MockObjectStore) SaveAll(store string, src ...any) ([]string, error) {
	m.ctrl.T.Helper()
	varargs := []any{store}
	for _, a := range src {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SaveAll", varargs...)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveAll indicates an expected call of SaveAll.
func (mr *MockObjectStoreMockRecorder) SaveAll(store any, src ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{store}, src...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAll", reflect.TypeOf((*MockObjectStore)(nil).SaveAll), varargs...)
}

// Since mocks base method.
func (m *MockObjectStore) Since(id string, count, skip int, store string) (common.ObjectRows, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Since", id, count, skip, store)
	ret0, _ := ret[0].(common.ObjectRows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Since indicates an expected call of Since.
func (mr *MockObjectStoreMockRecorder) Since(id, count, skip, store any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Since", reflect.TypeOf((*MockObjectStore)(nil).Since), id, count, skip, store)
}

// Stats mocks base method.
func (m *MockObjectStore) Stats(store string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stats", store)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stats indicates an expected call of Stats.
func (mr *MockObjectStoreMockRecorder) Stats(store any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stats", reflect.TypeOf((*MockObjectStore)(nil).Stats), store)
}

// Update mocks base method.
func (m *MockObjectStore) Update(key, store string, src any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", key, store, src)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockObjectStoreMockRecorder) Update(key, store, src any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockObjectStore)(nil).Update), key, store, src)
}
