// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/osiloke/gostore/common (interfaces: ObjectRows)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/object_rows.go github.com/osiloke/gostore/common ObjectRows
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockObjectRows is a mock of ObjectRows interface.
type MockObjectRows struct {
	ctrl     *gomock.Controller
	recorder *MockObjectRowsMockRecorder
	isgomock struct{}
}

// MockObjectRowsMockRecorder is the mock recorder for MockObjectRows.
type MockObjectRowsMockRecorder struct {
	mock *MockObjectRows
}

// NewMockObjectRows creates a new mock instance.
func NewMockObjectRows(ctrl *gomock.Controller) *MockObjectRows {
	mock := &MockObjectRows{ctrl: ctrl}
	mock.recorder = &MockObjectRowsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectRows) EXPECT() *MockObjectRowsMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockObjectRows) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockObjectRowsMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockObjectRows)(nil).Close))
}

// LastError mocks base method.
func (m *MockObjectRows) LastError() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastError")
	ret0, _ := ret[0].(error)
	return ret0
}

// LastError indicates an expected call of LastError.
func (mr *MockObjectRowsMockRecorder) LastError() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastError", reflect.TypeOf((*MockObjectRows)(nil).LastError))
}

// Next mocks base method.
func (m *MockObjectRows) Next(arg0 any) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Next indicates an expected call of Next.
func (mr *MockObjectRowsMockRecorder) Next(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockObjectRows)(nil).Next), arg0)
}

// NextRaw mocks base method.
func (m *MockObjectRows) NextRaw() ([]byte, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextRaw")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// NextRaw indicates an expected call of NextRaw.
func (mr *MockObjectRowsMockRecorder) NextRaw() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextRaw", reflect.TypeOf((*MockObjectRows)(nil).NextRaw))
}
