// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/osiloke/gostore/common (interfaces: ObjectStore)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/object_store.go github.com/osiloke/gostore/common ObjectStore
//
// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	common "github.com/osiloke/gostore/common"
	gomock "go.uber.org/mock/gomock"
)

// MockObjectStore is a mock of ObjectStore interface.
type MockObjectStore struct {
	ctrl     *gomock.Controller
	recorder *MockObjectStoreMockRecorder
}

// MockObjectStoreMockRecorder is the mock recorder for MockObjectStore.
type MockObjectStoreMockRecorder struct {
	mock *MockObjectStore
}

// NewMockObjectStore creates a new mock instance.
func NewMockObjectStore(ctrl *gomock.Controller) *MockObjectStore {
	mock := &MockObjectStore{ctrl: ctrl}
	mock.recorder = &MockObjectStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectStore) EXPECT() *MockObjectStoreMockRecorder {
	return m.recorder
}

// All mocks base method.
func (m *MockObjectStore) All(arg0, arg1 int, arg2 string) (common.ObjectRows, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All", arg0, arg1, arg2)
	ret0, _ := ret[0].(common.ObjectRows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// All indicates an expected call of All.
func (mr *MockObjectStoreMockRecorder) All(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*MockObjectStore)(nil).All), arg0, arg1, arg2)
}

// AllCursor mocks base method.
func (m *MockObjectStore) AllCursor(arg0 string) (common.ObjectRows, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllCursor", arg0)
	ret0, _ := ret[0].(common.ObjectRows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllCursor indicates an expected call of AllCursor.
func (mr *MockObjectStoreMockRecorder) AllCursor(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllCursor", reflect.TypeOf((*MockObjectStore)(nil).AllCursor), arg0)
}

// AllWithinRange mocks base method.
func (m *MockObjectStore) AllWithinRange(arg0 map[string]any, arg1, arg2 int, arg3 string, arg4 common.ObjectStoreOptions) (common.ObjectRows, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllWithinRange", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(common.ObjectRows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllWithinRange indicates an expected call of AllWithinRange.
func (mr *MockObjectStoreMockRecorder) AllWithinRange(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllWithinRange", reflect.TypeOf((*MockObjectStore)(nil).AllWithinRange), arg0, arg1, arg2, arg3, arg4)
}

// BatchDelete mocks base method.
func (m *MockObjectStore) BatchDelete(arg0 []any, arg1 string, arg2 common.ObjectStoreOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelete", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDelete indicates an expected call of BatchDelete.
func (mr *MockObjectStoreMockRecorder) BatchDelete(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockObjectStore)(nil).BatchDelete), arg0, arg1, arg2)
}

// BatchFilterDelete mocks base method.
func (m *MockObjectStore) BatchFilterDelete(arg0 []map[string]any, arg1 string, arg2 common.ObjectStoreOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchFilterDelete", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchFilterDelete indicates an expected call of BatchFilterDelete.
func (mr *MockObjectStoreMockRecorder) BatchFilterDelete(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchFilterDelete", reflect.TypeOf((*MockObjectStore)(nil).BatchFilterDelete), arg0, arg1, arg2)
}

// BatchInsert mocks base method.
func (m *MockObjectStore) BatchInsert(arg0 []any, arg1 string, arg2 common.ObjectStoreOptions) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchInsert", arg0, arg1, arg2)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchInsert indicates an expected call of BatchInsert.
func (mr *MockObjectStoreMockRecorder) BatchInsert(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchInsert", reflect.TypeOf((*MockObjectStore)(nil).BatchInsert), arg0, arg1, arg2)
}

// BatchUpdate mocks base method.
func (m *MockObjectStore) BatchUpdate(arg0, arg1 []any, arg2 string, arg3 common.ObjectStoreOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdate", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdate indicates an expected call of BatchUpdate.
func (mr *MockObjectStoreMockRecorder) BatchUpdate(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdate", reflect.TypeOf((*MockObjectStore)(nil).BatchUpdate), arg0, arg1, arg2, arg3)
}

// Before mocks base method.
func (m *MockObjectStore) Before(arg0 string, arg1, arg2 int, arg3 string) (common.ObjectRows, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Before", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(common.ObjectRows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Before indicates an expected call of Before.
func (mr *MockObjectStoreMockRecorder) Before(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Before", reflect.TypeOf((*MockObjectStore)(nil).Before), arg0, arg1, arg2, arg3)
}

// Close mocks base method.
func (m *MockObjectStore) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockObjectStoreMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockObjectStore)(nil).Close))
}

// CreateDatabase mocks base method.
func (m *MockObjectStore) CreateDatabase() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDatabase")
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDatabase indicates an expected call of CreateDatabase.
func (mr *MockObjectStoreMockRecorder) CreateDatabase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDatabase", reflect.TypeOf((*MockObjectStore)(nil).CreateDatabase))
}

// CreateTable mocks base method.
func (m *MockObjectStore) CreateTable(arg0 string, arg1 any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTable", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTable indicates an expected call of CreateTable.
func (mr *MockObjectStoreMockRecorder) CreateTable(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTable", reflect.TypeOf((*MockObjectStore)(nil).CreateTable), arg0, arg1)
}

// Delete mocks base method.
func (m *MockObjectStore) Delete(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockObjectStoreMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockObjectStore)(nil).Delete), arg0, arg1)
}

// FilterBefore mocks base method.
func (m *MockObjectStore) FilterBefore(arg0 string, arg1 map[string]any, arg2, arg3 int, arg4 string, arg5 common.ObjectStoreOptions) (common.ObjectRows, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterBefore", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(common.ObjectRows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterBefore indicates an expected call of FilterBefore.
func (mr *MockObjectStoreMockRecorder) FilterBefore(arg0, arg1, arg2, arg3, arg4, arg5 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterBefore", reflect.TypeOf((*MockObjectStore)(nil).FilterBefore), arg0, arg1, arg2, arg3, arg4, arg5)
}

// FilterBeforeCount mocks base method.
func (m *MockObjectStore) FilterBeforeCount(arg0 string, arg1 map[string]any, arg2, arg3 int, arg4 string, arg5 common.ObjectStoreOptions) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterBeforeCount", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterBeforeCount indicates an expected call of FilterBeforeCount.
func (mr *MockObjectStoreMockRecorder) FilterBeforeCount(arg0, arg1, arg2, arg3, arg4, arg5 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterBeforeCount", reflect.TypeOf((*MockObjectStore)(nil).FilterBeforeCount), arg0, arg1, arg2, arg3, arg4, arg5)
}

// FilterCount mocks base method.
func (m *MockObjectStore) FilterCount(arg0 map[string]any, arg1 string, arg2 common.ObjectStoreOptions) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterCount", arg0, arg1, arg2)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterCount indicates an expected call of FilterCount.
func (mr *MockObjectStoreMockRecorder) FilterCount(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterCount", reflect.TypeOf((*MockObjectStore)(nil).FilterCount), arg0, arg1, arg2)
}

// FilterDelete mocks base method.
func (m *MockObjectStore) FilterDelete(arg0 map[string]any, arg1 string, arg2 common.ObjectStoreOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterDelete", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// FilterDelete indicates an expected call of FilterDelete.
func (mr *MockObjectStoreMockRecorder) FilterDelete(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterDelete", reflect.TypeOf((*MockObjectStore)(nil).FilterDelete), arg0, arg1, arg2)
}

// FilterGet mocks base method.
func (m *MockObjectStore) FilterGet(arg0 map[string]any, arg1 string, arg2 any, arg3 common.ObjectStoreOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterGet", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// FilterGet indicates an expected call of FilterGet.
func (mr *MockObjectStoreMockRecorder) FilterGet(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterGet", reflect.TypeOf((*MockObjectStore)(nil).FilterGet), arg0, arg1, arg2, arg3)
}

// FilterGetAll mocks base method.
func (m *MockObjectStore) FilterGetAll(arg0 map[string]any, arg1, arg2 int, arg3 string, arg4 common.ObjectStoreOptions) (common.ObjectRows, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterGetAll", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(common.ObjectRows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterGetAll indicates an expected call of FilterGetAll.
func (mr *MockObjectStoreMockRecorder) FilterGetAll(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterGetAll", reflect.TypeOf((*MockObjectStore)(nil).FilterGetAll), arg0, arg1, arg2, arg3, arg4)
}

// FilterReplace mocks base method.
func (m *MockObjectStore) FilterReplace(arg0 map[string]any, arg1 any, arg2 string, arg3 common.ObjectStoreOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterReplace", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// FilterReplace indicates an expected call of FilterReplace.
func (mr *MockObjectStoreMockRecorder) FilterReplace(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterReplace", reflect.TypeOf((*MockObjectStore)(nil).FilterReplace), arg0, arg1, arg2, arg3)
}

// FilterSince mocks base method.
func (m *MockObjectStore) FilterSince(arg0 string, arg1 map[string]any, arg2, arg3 int, arg4 string, arg5 common.ObjectStoreOptions) (common.ObjectRows, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterSince", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(common.ObjectRows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterSince indicates an expected call of FilterSince.
func (mr *MockObjectStoreMockRecorder) FilterSince(arg0, arg1, arg2, arg3, arg4, arg5 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterSince", reflect.TypeOf((*MockObjectStore)(nil).FilterSince), arg0, arg1, arg2, arg3, arg4, arg5)
}

// FilterUpdate mocks base method.
func (m *MockObjectStore) FilterUpdate(arg0 map[string]any, arg1 any, arg2 string, arg3 common.ObjectStoreOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterUpdate", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// FilterUpdate indicates an expected call of FilterUpdate.
func (mr *MockObjectStoreMockRecorder) FilterUpdate(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterUpdate", reflect.TypeOf((*MockObjectStore)(nil).FilterUpdate), arg0, arg1, arg2, arg3)
}

// Get mocks base method.
func (m *MockObjectStore) Get(arg0, arg1 string, arg2 any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockObjectStoreMockRecorder) Get(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockObjectStore)(nil).Get), arg0, arg1, arg2)
}

// GetByField mocks base method.
func (m *MockObjectStore) GetByField(arg0, arg1, arg2 string, arg3 any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByField", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetByField indicates an expected call of GetByField.
func (mr *MockObjectStoreMockRecorder) GetByField(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByField", reflect.TypeOf((*MockObjectStore)(nil).GetByField), arg0, arg1, arg2, arg3)
}

// GetByFieldsByField mocks base method.
func (m *MockObjectStore) GetByFieldsByField(arg0, arg1, arg2 string, arg3 []string, arg4 any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByFieldsByField", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetByFieldsByField indicates an expected call of GetByFieldsByField.
func (mr *MockObjectStoreMockRecorder) GetByFieldsByField(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByFieldsByField", reflect.TypeOf((*MockObjectStore)(nil).GetByFieldsByField), arg0, arg1, arg2, arg3, arg4)
}

// GetStore mocks base method.
func (m *MockObjectStore) GetStore() any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStore")
	ret0, _ := ret[0].(any)
	return ret0
}

// GetStore indicates an expected call of GetStore.
func (mr *MockObjectStoreMockRecorder) GetStore() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStore", reflect.TypeOf((*MockObjectStore)(nil).GetStore))
}

// Query mocks base method.
func (m *MockObjectStore) Query(arg0, arg1 map[string]any, arg2, arg3 int, arg4 string, arg5 common.ObjectStoreOptions) (common.ObjectRows, common.AggregateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(common.ObjectRows)
	ret1, _ := ret[1].(common.AggregateResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Query indicates an expected call of Query.
func (mr *MockObjectStoreMockRecorder) Query(arg0, arg1, arg2, arg3, arg4, arg5 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockObjectStore)(nil).Query), arg0, arg1, arg2, arg3, arg4, arg5)
}

// Replace mocks base method.
func (m *MockObjectStore) Replace(arg0, arg1 string, arg2 any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Replace", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Replace indicates an expected call of Replace.
func (mr *MockObjectStoreMockRecorder) Replace(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Replace", reflect.TypeOf((*MockObjectStore)(nil).Replace), arg0, arg1, arg2)
}

// Save mocks base method.
func (m *MockObjectStore) Save(arg0, arg1 string, arg2 any) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockObjectStoreMockRecorder) Save(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockObjectStore)(nil).Save), arg0, arg1, arg2)
}

// SaveAll mocks base method.
func (m *MockObjectStore) SaveAll(arg0 string, arg1 ...any) ([]string, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SaveAll", varargs...)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveAll indicates an expected call of SaveAll.
func (mr *MockObjectStoreMockRecorder) SaveAll(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAll", reflect.TypeOf((*MockObjectStore)(nil).SaveAll), varargs...)
}

// Since mocks base method.
func (m *MockObjectStore) Since(arg0 string, arg1, arg2 int, arg3 string) (common.ObjectRows, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Since", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(common.ObjectRows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Since indicates an expected call of Since.
func (mr *MockObjectStoreMockRecorder) Since(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Since", reflect.TypeOf((*MockObjectStore)(nil).Since), arg0, arg1, arg2, arg3)
}

// Stats mocks base method.
func (m *MockObjectStore) Stats(arg0 string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stats", arg0)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stats indicates an expected call of Stats.
func (mr *MockObjectStoreMockRecorder) Stats(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stats", reflect.TypeOf((*MockObjectStore)(nil).Stats), arg0)
}

// Update mocks base method.
func (m *MockObjectStore) Update(arg0, arg1 string, arg2 any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockObjectStoreMockRecorder) Update(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockObjectStore)(nil).Update), arg0, arg1, arg2)
}
